### ISSUE TITLE
Support for jdk13?

### ISSUE THREAD

**Issue by bolunli11** [google/allocation-instrumenter#34]
It seems that the allocation instrumenter cannot work on jdk13. Can I know the reason? Like, some ASM APIs used in the allocation instrumenter aren't supported by jdk13 yet? Thank you!

**Comment by jhmanson** [comment]
I don't have a problem with it at head.  Are you building from head, or using a prebuilt?

**Comment by Krisgg521** [comment]
Actually I can build it without error. Then I use the allocation instrumenter .jar file as a Java agent to profile some Java programs. The command is like: java -javaagent:allocation_instrumenter.jar java_application. I got below error messages. In fact, I can use the same way to profile Java programs with older JDK successfully, like JDK11. So I'm wondering that either asm or java.lang.instrument API is not supported by JDK13.

Error Message:
WARNING: Failed to instrument class.
java.lang.IllegalArgumentException: Unsupported class file major version 57
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.<init>(ClassReader.java:176)
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.<init>(ClassReader.java:158)
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.<init>(ClassReader.java:146)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument(AllocationInstrumenter.java:312)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument(AllocationInstrumenter.java:340)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.transform(AllocationInstrumenter.java:294)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1257)
	at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2199)
	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:118)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:661)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:630)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at org.dacapo.harness.DacapoClassLoader.loadClass(DacapoClassLoader.java:123)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.dacapo.lusearch.Search$QueryProcessor.<init>(Search.java:213)
	at org.dacapo.lusearch.Search$QueryThread.run(Search.java:179)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:1212), pid=41361, tid=41486
#  guarantee((retry_count++ < 100)) failed: Could not resolve to latest version of redefined method
#
# JRE version: OpenJDK Runtime Environment (13.0.1+9) (build 13.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM (13.0.1+9, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xc85571]  SharedRuntime::resolve_helper(JavaThread*, bool, bool, Thread*)+0xf1

**Comment by jhmanson** [comment]
That shouldn't happen at head.  Are you sure you are compiling from head?

Can you double-check the version of ASM being pulled into your build?

**Comment by jhmanson** [comment]
I'll probably close this if it can't be repro'd at head.
