### ISSUE TITLE
Failing to instrument classes due to outdated ASM version

### ISSUE THREAD

**Issue by lukeramsden** [google/allocation-instrumenter#51]
The upgrade of ASM to 9.2 in order to support JDK 17 does "work" - but, due to this library still specifying ASM7 when loading the Java Agent, some warnings happen:

```
WARNING: Failed to instrument class.
java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
	at com.google.monitoring.runtime.instrumentation.asm.ClassVisitor.visitPermittedSubclass(ClassVisitor.java:281)
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.accept(ClassReader.java:706)
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.accept(ClassReader.java:424)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument(AllocationInstrumenter.java:200)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument(AllocationInstrumenter.java:220)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.transform(AllocationInstrumenter.java:174)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.bootstrap(AllocationInstrumenter.java:157)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.premain(AllocationInstrumenter.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenterBootstrap.premain(AllocationInstrumenterBootstrap.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
```

Doing some quick debugging, this specific stack trace is when visiting `java.lang.reflect.Constructor`, which extends from a sealed class `java.lang.reflect.Executable`. What are the implications of this warning - is it just that non-instrumented classes will not show up as calls to the allocation sampler callback (i.e. all record classes and permitted subclasses will not show up)? And what are the blockers to using ASM8/9 over 7 - is there significant work involved in supporting additional class visitors, or could it be a simple version bump (not used ASM before)?

**Comment by lukeramsden** [comment]
I've done some playing around and simply changing the `super(Opcodes.ASM7, ...)` calls in various classes to instead references `Opcodes.ASM9` stops the warnings and doesn't seem to break any of our unit tests that assert on code being allocation-free, although the code under test doesn't actually use records or permitted subclasses as mentioned in the warnings.

**Comment by cpovirk** [comment]
Thanks. @cushon made this change internally recently—and also started a conversation about who exactly owns this code after the various changes to our Java teams over the years.

Perhaps whoever owns this will set up some automation so that future changes are tested and mirrored out automatically... which would be useful, as I notice when manually mirroring this change out that it needs a corresponding change to the open-source build setup before it will build... :)

**Comment by lukeramsden** [comment]
Nice to hear. I opened a PR before you wrote this but happy to have that closed and see any internal changes mirrored outwardly. It's a very nice library, the warnings due to ASM9 are just unfortunate :smiley:

**Comment by lukeramsden** [comment]
Thanks a bunch! Great stuff
